name: Branch Conditional Workflow
on: push

jobs:
  detect-branch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "현재 브랜치: ${{ github.ref }}"

      - name: Dev Branch Only
        if: ${{ github.ref == 'dev' }}
        run: |
          echo "개발 브랜치이므로 테스트 실행!"

      - name: Main Branch Only
        if: ${{ github.ref == 'main' }}
        run: |
          echo "운영 브랜치이므로 배포 진행!"